on:
  pull_request:
    types:
      - opened
    paths:
      - '*.proto'
  workflow_dispatch:
name: "buf breaking check"
jobs:
  validate-protos:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v2
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1
      # Run breaking change detection against the `main` branch
      - name: "do bufbuild/buf-breaking-action"
        uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/sourcegraph/zoekt.git#branch=main'
